apiVersion: v1
kind: Service
metadata: 
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 8181         #porta que foi criada no k3d (8181:31000@loadbalancer). ou seja, a porta permite o acesso ao cluster
      targetPort: 8080    #porta referente a aplicação desenvolvida
      nodePort: 31000     #porta que referece ao nodo criado pelo k3d, (8181:31000@loadbalancer).
  type: NodePort